### ISSUE TITLE
Story ids?

### ISSUE THREAD

**Issue by mikekestemont** [smilli/fanfiction#1]
Thanks for this great tool! I wanted to give it a try (in the context of authorship attribution) but I was wondering how one should obtain the story IDs to feed to the scraper? Can you just naively start counting from 1 or is there a list somewhere? Thanks in advance for any pointers.

**Comment by hayesall** [comment]
@mikekestemont Here's a short bash script that pulls the first 25 pages of Harry Potter story IDs:

```bash
#!/bin/bash
BASE="https://www.fanfiction.net/book/Harry-Potter/?srt=1&r=10&p="
for i in {1..25}; do
    URL=$BASE$i
    echo "$URL"
    PAGE="`wget --no-check-certificate -q -O - $URL`"
    echo "$PAGE" | grep "class=stitle" | cut -c117-137 | cut -d'/' -f 3 >> sids.txt
    sleep 3
done
```

This will create a URL corresponding to a certain page, download it, find the "stitle", cut between characters 117-137, drop the sids into sids.txt, then pause for a few seconds to comply with TOS.

If you want all of the sids, figure out what the total number of pages is and plug that into the for loop.

**Comment by mikekestemont** [comment]
Awesome, thanks for the help!
